### ISSUE TITLE
readme typo

### ISSUE THREAD

**Issue by yw662** [tokers/lua-resty-requests#18]
in `readme.md`
     
$ opm get thibaultcha/lua-resty-mlcache

shouldnt it be something else ?

**Comment by tokers** [comment]
@yw662 
Oops... So embarrassed, that part was copied from thibaultcha's lua-resty-mlcache.

I will fix this typo :). Thanks for your report.

**Comment by tokers** [comment]
I have fixed this embarrassing typo in this commit: https://github.com/tokers/lua-resty-requests/commit/61ef0dec7672b825650f29f6057c3c16531fd532.

Now I'm going to close this issue. Thanks again!
