### ISSUE TITLE
README timeouts misrepresent

### ISSUE THREAD

**Issue by jetz** [tokers/lua-resty-requests#21]
```
timeouts, an array-like table, timeouts[1], timeouts[2] and timeouts[3] represents connect timeout, send timeout and read timeout respectively (in seconds).
```
I think it's `in milliseconds` instead of `in seconds`, just as [tcpsock:settimeouts](https://github.com/openresty/lua-nginx-module#tcpsocksettimeouts) .

**Comment by jetz** [comment]
@tokers PR Done.

**Comment by tokers** [comment]
https://github.com/tokers/lua-resty-requests/pull/22

The related Pull Request was merged. I'm closing this issue now.
