### ISSUE TITLE
typo in README

### ISSUE THREAD

**Issue by sjnam** [tokers/lua-resty-requests#23]
README.markdown -- Installation -- OPM
```
opm get thibaultcha/lua-resty-requests
```
thibaultcha ??? 

```
opm get tokers/lua-resty-requests
```

Thank you for providing a useful resty module!

**Comment by tokers** [comment]
@sjnam 

🤣Thanks for your report. Actually this paragraph is copied from Thibault's lua-resty-mlcache. I will fix this typo, awkward....
