### ISSUE TITLE
lua-resty-requests move to production ready 

### ISSUE THREAD

**Issue by JarenGlover** [tokers/lua-resty-requests#24]
Hi, 

I see you recently moved the project from experimental to production (8079b64). 
Congrats!

What was the big driver for moving it from experimental to production? 

Thanks in advance.

**Comment by tokers** [comment]
We use it (v0.7) in one of our reverse proxy cluster for serval months and it’s stable.

**Comment by tokers** [comment]
@JarenGlover 
Any other problems? I wanna close this issue now.

**Comment by JarenGlover** [comment]
@tokers perfect. thanks
