### ISSUE TITLE
Compatible with "Expect: 100-Continue"

### ISSUE THREAD

**Issue by timebug** [tokers/lua-resty-requests#26]
As described in the [RFC7231](https://tools.ietf.org/html/rfc7231#section-5.1.1
) documentation, the Expect field-value is case-insensitive. 

And there are some popular HTTP client libraries that use `100-Continue` as the Expect field-value. Such as [guzzle](https://github.com/guzzle/guzzle/blob/003757426cdd50fbad1c34cdbcc8a55f70a4fe8b/src/PrepareBodyMiddleware.php#L88) (an extensible PHP HTTP client).

So we should make [this code](https://github.com/tokers/lua-resty-requests/blob/2539481d8f84fec86ad6a7171474ac20b9fa28ed/lib/resty/requests/request.lua#L149) more compatible.

**Comment by tokers** [comment]
Nice Catch. I will fix it.

**Comment by tokers** [comment]
@timebug Fixed. See https://github.com/tokers/lua-resty-requests/commit/9b57930bc964165ce51fcf87d49b4db55c8fb969 for the details.

**Comment by timebug** [comment]
@tokers Oked, just added some test cases.
