### ISSUE TITLE
Do you support grpc?

### ISSUE THREAD

**Issue by majc08149** [tokers/lua-resty-requests#28]
Here is my code：
	
     local p, err = proto.new("proto-file/student.proto")
	if err then
        ngx.log(ngx.ERR, ("proto load error: %s"):format(err))
        return
	end
	local m = util.find_method(p, "htsc.grpc.streamtest.Greeter", "GetStudentFamily")
	if not m then
		return
	end
	-- Build request binary as method input type from request data (query string, post body, or JSON body)
	local encoded = pb.encode(m.input_type, util.map_message(m.input_type, default_values or {}))
	local size = string.len(encoded)
	 -- Prepend gRPC specific prefix data
    -- request is compressed (always 0)
    -- requesdt body size (4 bytes)
    local prefix = {
		string.char(0),
		string.char(bit.band(bit.rshift(size, 24), 0xFF)),
		string.char(bit.band(bit.rshift(size, 16), 0xFF)),
		string.char(bit.band(bit.rshift(size, 8), 0xFF)),
		string.char(bit.band(size, 0xFF))
	  }
	  local message = table.concat(prefix, "") .. encoded
	  local url = "192.168.88.72:50033"
	  local opts = {
		  --stream = false,
		  http2 = true,
		  headers ={
			[":path"] = "/htsc.grpc.streamtest.Greeter/GetStudentFamily",
			["te"] = "trailers",
			["content-type"] = "application/grpc",
			["user-agent"] = "grpc-c++/1.24.0-dev grpc-c/8.0.0 (linux; chttp2; ganges)",
			["grpc-accept-encoding"] = "identity,deflate,gzip",
			["accept-encoding"] = "identity,gzip",
		  },
		  body = message  
	  }
	  local r, err = req.request("POST",url,opts)
	  if not r then
		ngx.log(ngx.ERR, err)
		return
	  end
	  local body = r:body()
      ngx.print(body)

but  the body is not available for the response，my grpc server return response OK, also have body

**Comment by tokers** [comment]
@majc08149 Thanks for the report. I will try to reproduce it on my machine.

**Comment by majc08149** [comment]
in file  http2.lua，the function read_body，it seems that  if there is a header, the the following data must have a data as body. the grpc response is  header-->data-->header，so i think  it is the problem  

function _M:read_body(stream)
    if stream.done then
        return ""
    end

    local session = stream.session

    while not self.cached_body do
        local ok, err = handle_frame(self, session, stream)
        if not ok then
            return nil, err
        end
    end

    local body = self.cached_body.data
    self.cached_body = self.cached_body.next

    return body
end

**Comment by tokers** [comment]
> in file http2.lua，the function read_body，it seems that if there is a header, the the following data must have a data as body. the grpc response is header-->data-->header，so i think it is the problem
> 
> function _M:read_body(stream)
> if stream.done then
> return ""
> end
> 
> ```
> local session = stream.session
> 
> while not self.cached_body do
>     local ok, err = handle_frame(self, session, stream)
>     if not ok then
>         return nil, err
>     end
> end
> 
> local body = self.cached_body.data
> self.cached_body = self.cached_body.next
> 
> return body
> ```
> 
> end

So have you tried to remove the trailing headers? By just sending a trivial HTTP/2 request.

**Comment by tokers** [comment]
@majc08149 I have observed this problem, I will try to fix it.

**Comment by tokers** [comment]
@majc08149 I have submitted a PR to fix this problem, just see https://github.com/tokers/lua-resty-http2/pull/4 for the details.
