### ISSUE TITLE
unused arg `headers`

### ISSUE THREAD

**Issue by moonming** [tokers/lua-resty-requests#8]
the second arg `headers` is coverd by `session.headers`: https://github.com/tokers/lua-resty-requests/blob/c904f4a0061c58040a55e60ce651aae1246210ed/lib/resty/requests/request.lua#L62

**Comment by tokers** [comment]
@moonming Thanks for the report! The `headers` is really useless.

**Comment by tokers** [comment]
@moonming I have pushed a commit here: https://github.com/tokers/lua-resty-requests/pull/10/commits/1bbc023ef5765bf894c940719877ea6115d2a98d
